Feature/generate title links
arturodfrontu/blog-js pull request #2
Opened 2020-11-18 18:38 UTC by arturodfrontu

It works ;)

2020-11-19 20:48 UTC, arturodfrontu commented on js/script.js
> +    function removeElements(elements){
Fixed 👍 :)

2020-11-20 08:47 UTC, Neonides requested changes

2020-11-20 08:47 UTC, Neonides commented on js/script.js
> +function removeElements(elements){
Tutaj tak naprawdę przekazujesz jeden `element` a nie `elements`

2020-11-20 09:50 UTC, Neonides approved these changes

2020-12-03 18:32 UTC, merged